#!/bin/sh
set -e
set -x
if [ "$1" != "" ]; then
  HTTPPATH=$1
fi
CDIR=../certs
curl -k \
-s  -w "httpcode: %{http_code}\n" \
-E ${CDIR}/envoy.client-combined.pem \
 https://server.test.com:9090/${HTTPPATH}
